# Generated by Django 3.2.7 on 2022-03-08 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('telegram_id', models.BigIntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.CharField(max_length=200)),
                ('player_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('opponent_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('tour', models.IntegerField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bots.division')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opponent', to='bots.user')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player', to='bots.user')),
            ],
        ),
    ]
