# Generated by Django 3.2.7 on 2022-05-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20220515_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='last_command',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
