# Generated by Django 3.2.7 on 2022-05-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_alter_telegramuser_last_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='last_command',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
